name: Compute Bumped Version
description: >
  Computes the next semantic version based on commit messages and changed files since the last version tag.

inputs:
  force-patch-if-no-commit-token:
    description: Force patch bump if no [major], [minor], [patch], or [fix] found in commit message(s)
    required: false
    default: "false"
  ignore-paths:
    description: Newline-delimited list of file/directory globs to ignore when checking changed files
    required: false
    default: ""

outputs:
  version:
    description: The next semantic version (empty string if no bump is needed)
    value: ${{ steps.compute.outputs.version }}

runs:
  using: "composite"
  steps:
    - name: Is this most recent commit?
      shell: bash
      run: |
        set -euo pipefail
        echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"

        git fetch &> /dev/null
        if [[ $(git status -sb | grep behind) ]]; then
          echo "::error::this commit is not most recent on this branch -- rest of workflow should be halted"
          exit 1
        fi

    - id: compute
      env:
        FORCE_PATCH_IF_NO_COMMIT_TOKEN: ${{ inputs.force-patch-if-no-commit-token }}
        IGNORE_PATHS: ${{ inputs.ignore-paths }}
      shell: bash
      run: |
        set -euo pipefail
        echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
        echo

        # get the latest semantic-version style tag
        _latest_semver_tag=$(git tag --sort=-creatordate | grep -E '^v?[0-9]+\.[0-9]+\.[0-9]+$' | head -n1 || true)
        echo "Latest semantic-version style tag: $_latest_semver_tag"
        echo
        if [ -z "$_latest_semver_tag" ]; then
            echo "No previous semver tag found — using 0.0.0"
            echo "version=0.0.0" >> "$GITHUB_OUTPUT"
            exit 0
        else
            export LATEST_SEMVER_TAG_NO_V="${_latest_semver_tag#v}"
        fi

        # get info on what's changed since that tag
        export FIRST_COMMIT=$(git rev-list -n 1 "$_latest_semver_tag")
        echo "Looking at what's changed since $_latest_semver_tag / $FIRST_COMMIT..."
        echo
        
        export CHANGED_FILES=$(git diff --name-only "$FIRST_COMMIT"..HEAD)  # has newlines
        echo "Changed files:"
        echo "<start>"
        echo "$CHANGED_FILES"
        echo "<end>"
        echo
        
        # NOTE: commit logs are retrieved in python script b/c newlines are a pain

        # get next version
        VERSION=$(python ${{ github.action_path }}/compute_next_version.py)
        echo
        
        # last minute check that branch has not been updated
        git fetch &> /dev/null
        if [[ $(git status -sb | grep behind) ]]; then
          echo "this commit is not most recent on this branch -- rest of action will be aborted"
          exit 0
        fi

        # supply output
        if [ -z "$VERSION" ]; then
            echo "No version bump needed"
            echo "version=" >> "$GITHUB_OUTPUT"
        else
            echo "Next version: $VERSION"
            echo "version=$VERSION" >> "$GITHUB_OUTPUT"
        fi
